# Generated by Django 4.1 on 2022-08-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='refresh_time',
            new_name='refresh_token',
        ),
    ]
