# Generated by Django 4.1 on 2022-08-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_connect', '0002_rename_refresh_time_spotifytoken_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
