# Generated by Django 4.1 on 2022-08-11 00:18

from django.db import migrations, models
import myDjangoApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=myDjangoApp.models.generate_code, max_length=8, unique=True),
        ),
    ]
